version: "3.1"

services:
  db:
    image: postgres
    container_name: shopapi_postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "shopapi_db"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"